version: '3'

services:
  sys_node:
    hostname: sys_node
    image: sys_node
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        ROS_DISTRO: humble
    environment:
      - "PYTHONUNBUFFERED=1" # important to show error messages if a ros service crashes!
    networks:
    - sys_test

networks:
  sys_test:
    external: true