services:
  sys_info:
    hostname: sys_info
    image: sys_info
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        ROS_DISTRO: jazzy
    environment:
      - "PYTHONUNBUFFERED=1" # important to show error messages if a ros service crashes!
      - ROS_DOMAIN_ID=$ROS_DOMAIN_ID
    network_mode: host
