# System Information
NetworkDevice[] network_devices
# TODO: detailed WiFi information by parsing /proc/net/wireless
# TODO: Information about active I2C, GPIO etc.
# TODO: current temperatures from sensors service (if available)
# TODO: running processes, used memory and disc space
# TODO: special raspberry pi information like undervoltage information or temperatures (if available from https://www.raspberrypi.com/documentation/computers/os.html#vcgencmd)
